Hyung-A/CollaTime_Project

CollaTime/build.gradle
CollaTime/src/main/resources/application.yml

#6_feature/ProjectPage
<br>
Project Domain의 프로젝트 참여 및 생성하기 모달창 만들었습니다.
<br>
...
<br>

241029_feature/6-ProjectPage

---

CollaTime/src/main/resources/application.yml
CollaTime/src/main/resources/templates/common/header.html
CollaTime/src/main/resources/templates/common/main.html

#(작업 이슈번호 적어주세요.)
<br>
(구현한 코딩 기능 및 변경된 사항 적어주세요.) 
<br>
<br>

2024.10.29_feature/3_header-footer

---

CollaTime/src/main/java/com/ohgiraffers/collatime/user/controller/UserController.java
CollaTime/src/main/resources/static/css/user/login.css
CollaTime/src/main/resources/static/css/user/signup.css
CollaTime/src/main/resources/templates/auth/login.html
CollaTime/src/main/resources/templates/user/signup.html

#12 
<br>
로그인 버튼을 누를 시 나오는 모달창을 만들었습니다.
<br>
<br>

[feature]#12 로그인 모달창

---

CollaTime/src/main/java/com/ohgiraffers/collatime/user/controller/UserController.java
CollaTime/src/main/resources/static/css/user/login.css
CollaTime/src/main/resources/static/css/user/signup.css
CollaTime/src/main/resources/templates/auth/login.html
CollaTime/src/main/resources/templates/user/signup.html

#14 
<br>
회원가입 기본 페이지
<br>
<br>

[Feature]#14 SignupPage

---

CollaTime/src/main/resources/static/css/project/projectMain.css
CollaTime/src/main/resources/templates/project/ProjectMain.html

#6 
<br>
project 도메인의 메인 page 레이아웃 완성했습니다.
<br>
<br>

241030_feature/6-projectPage

---

CollaTime/src/main/resources/static/css/schedule/delete.css
CollaTime/src/main/resources/static/css/schedule/deletecheck.css
CollaTime/src/main/resources/static/css/schedule/details.css
CollaTime/src/main/resources/static/css/schedule/makeschedule.css
CollaTime/src/main/resources/static/css/schedule/modify.css
CollaTime/src/main/resources/static/css/schedule/modifycheck.css
CollaTime/src/main/resources/templates/common/SMALLMD.html
CollaTime/src/main/resources/templates/schedule/delete.html
CollaTime/src/main/resources/templates/schedule/deletecheck.html
CollaTime/src/main/resources/templates/schedule/details.html
CollaTime/src/main/resources/templates/schedule/makeschedule.html
CollaTime/src/main/resources/templates/schedule/modify.html
CollaTime/src/main/resources/templates/schedule/modifycheck.html

#(작업 이슈번호 적어주세요.)
#11 
<br>
(구현한 코딩 기능 및 변경된 사항 적어주세요.) 
스케줄 모달창
<br>
<br>

241031_feature/11-scheduleModal

---

CollaTime/src/main/resources/static/css/common/header.css
CollaTime/src/main/resources/static/css/common/main.css
CollaTime/src/main/resources/templates/common/header.html
CollaTime/src/main/resources/templates/common/main.html

#3 
<br>
헤더 푸터 완성했습니다
<br>
<br>

241030_feature/3-header-and-footer

---

CollaTime/src/main/java/com/ohgiraffers/collatime/project/controller/ProjectController.java
CollaTime/src/main/java/com/ohgiraffers/collatime/project/model/dao/ProjectMapper.java
CollaTime/src/main/java/com/ohgiraffers/collatime/project/model/dto/ProjectDTO.java
CollaTime/src/main/java/com/ohgiraffers/collatime/project/model/service/ProjectService.java
CollaTime/src/main/resources/mappers/project/ProjectMapper.xml
CollaTime/src/main/resources/static/css/project/modalCreateOrJoin.css
CollaTime/src/main/resources/static/css/project/modalCreateProject.css
CollaTime/src/main/resources/templates/project/ProjectMain.html

#24 
<br>
프로젝트 모달에서 DB로 연결하는 작업 했는데 계속 오류납니다....
<br>
<br>

241101_feature/24-modalCreateProject

---

CollaTime/src/main/java/com/ohgiraffers/collatime/project/controller/ProjectController.java
CollaTime/src/main/java/com/ohgiraffers/collatime/project/model/dao/ProjectMapper.java
CollaTime/src/main/java/com/ohgiraffers/collatime/project/model/dto/ProjectDTO.java
CollaTime/src/main/java/com/ohgiraffers/collatime/project/model/service/ProjectService.java
CollaTime/src/main/resources/mappers/project/ProjectMapper.xml
CollaTime/src/main/resources/static/css/project/modalUpdateProject.css
CollaTime/src/main/resources/static/css/project/projectMain.css
CollaTime/src/main/resources/templates/common/BIGMD.html
CollaTime/src/main/resources/templates/common/MIDDLEMD.html
CollaTime/src/main/resources/templates/common/SMALLMD.html
CollaTime/src/main/resources/templates/common/header.html
CollaTime/src/main/resources/templates/common/main.html
CollaTime/src/main/resources/templates/project/CreateOrJoin.html
CollaTime/src/main/resources/templates/project/ProjectMain.html
CollaTime/src/main/resources/templates/project/modalCreateProject.html
CollaTime/src/main/resources/templates/project/modalInviteMemeber.html
CollaTime/src/main/resources/templates/project/modalUpdateProject.html

#48 
<br>
DB에서 데이터 내용 가져와서 화면에 띄어지긴 하지만 아직 온전히 가져오지 못해서 다듬어야합니다.
<br>
<br>

241104_feature/48-projectSpecificSelect

---

CollaTime/src/main/java/com/ohgiraffers/collatime/project/controller/ProjectController.java
CollaTime/src/main/resources/mappers/project/ProjectMapper.xml
CollaTime/src/main/resources/static/css/project/modalSelectProject.css
CollaTime/src/main/resources/templates/project/ProjectMain.html

#48 
<br>
DB에서 불러오는 데이터가 화면에 제대로 안띄어집니다. 
여러 방법으로 시도하는 중입니다.
<br>
<br>

241105_feature/48-projectSpecificSelect

---

CollaTime/src/main/java/com/ohgiraffers/collatime/schedule/controller/ScheduleController.java
CollaTime/src/main/java/com/ohgiraffers/collatime/schedule/model/dao/ScheduleMapper.java
CollaTime/src/main/java/com/ohgiraffers/collatime/schedule/model/dto/ScheduleDTO.java
CollaTime/src/main/java/com/ohgiraffers/collatime/schedule/model/servcie/ScheduleService.java
CollaTime/src/main/resources/mappers/schedule/scheduleMapper.xml
CollaTime/src/main/resources/static/css/schedule/empty.css
CollaTime/src/main/resources/static/css/schedule/main.css
CollaTime/src/main/resources/static/css/schedule/makeschedule.css
CollaTime/src/main/resources/templates/common/footer.html
CollaTime/src/main/resources/templates/schedule/calendar.html
CollaTime/src/main/resources/templates/schedule/empty.html
CollaTime/src/main/resources/templates/schedule/main.html
CollaTime/src/main/resources/templates/schedule/makeschedule.html

#(작업 이슈번호 적어주세요.)
#52 
<br>
(구현한 코딩 기능 및 변경된 사항 적어주세요.) 
스케줄 메인화면 및 추가하기
<br>
<br>

241105_feature/52-스케줄 메인화면, 추가하기

---

CollaTime/src/main/java/com/ohgiraffers/collatime/project/controller/ProjectController.java
CollaTime/src/main/resources/templates/project/projectmain.html

#69 
<br>
입력받은 이메일을 화면에 바로 띄우고 취소 버튼 클릭 시 배열 삭제되는 것까지만 구현했습니다. 
저번에 올렸던 기능에서 조금 더 보완된 내용입니다.(시각적으로는 보이지 않아요...)
<br>
<br>

241108_feature/69-sendInviteMail

---

CollaTime/src/main/java/com/ohgiraffers/collatime/mypage/controller/MypageController.java
CollaTime/src/main/java/com/ohgiraffers/collatime/mypage/model/service/MypageService.java
CollaTime/src/main/java/com/ohgiraffers/collatime/user/model/dao/UserMapper.java
CollaTime/src/main/java/com/ohgiraffers/collatime/user/model/dto/UserDTO.java
CollaTime/src/main/java/com/ohgiraffers/collatime/user/model/service/UserService.java
CollaTime/src/main/resources/mappers/user/UserMapper.xml
CollaTime/src/main/resources/static/css/mypage/modifyuser.css
CollaTime/src/main/resources/static/css/mypage/myinqiury.css
CollaTime/src/main/resources/static/css/mypage/mypagemain.css
CollaTime/src/main/resources/static/css/mypage/resultsmallmodal.css
CollaTime/src/main/resources/templates/mypage/modifyusermodal.html
CollaTime/src/main/resources/templates/mypage/myinquiry.html
CollaTime/src/main/resources/templates/mypage/mypagemain.html
CollaTime/src/main/resources/templates/mypage/resultsmallmodal.html
CollaTime/src/main/resources/templates/user/findidandpwd.html
CollaTime/src/main/resources/templates/user/signup.html

#72 
<br>
회원정보 수정 다 만들었습니다.
현재 탈퇴는 아직 안 만들었습니다.
<br>
<br>

11/08 Feature/72-modifyUser

---

CollaTime/src/main/java/com/ohgiraffers/collatime/schedule/controller/ScheduleController.java
CollaTime/src/main/java/com/ohgiraffers/collatime/schedule/model/dao/ScheduleMapper.java
CollaTime/src/main/java/com/ohgiraffers/collatime/schedule/model/service/ScheduleService.java
CollaTime/src/main/resources/mappers/schedule/scheduleMapper.xml
CollaTime/src/main/resources/static/css/schedule/list.css
CollaTime/src/main/resources/templates/schedule/calendar.html
CollaTime/src/main/resources/templates/schedule/details.html
CollaTime/src/main/resources/templates/schedule/list.html
CollaTime/src/main/resources/templates/schedule/makeschedule.html

#52 
<br>
스케줄 추가하기 db 연동 완료
<br>
<br>

241108_feature/52-스케줄 메인화면, 스케줄 DB 연동하기

---

CollaTime/src/main/java/com/ohgiraffers/collatime/schedule/controller/ScheduleController.java
CollaTime/src/main/java/com/ohgiraffers/collatime/schedule/model/dao/ScheduleMapper.java
CollaTime/src/main/java/com/ohgiraffers/collatime/schedule/model/service/ScheduleService.java
CollaTime/src/main/resources/mappers/schedule/scheduleMapper.xml
CollaTime/src/main/resources/static/css/schedule/list.css
CollaTime/src/main/resources/templates/schedule/calendar.html
CollaTime/src/main/resources/templates/schedule/list.html

#76 
<br>
날짜 눌렀을 때 스케줄이 있으면 모달창에 스케줄 나오도록 
<br>
<br>

241111_feature/76-스케줄 조회 모달창

---

CollaTime/src/main/java/com/ohgiraffers/collatime/schedule/controller/ScheduleController.java

#76 
<br>
(구현한 코딩 기능 및 변경된 사항 적어주세요.) 
<br>
<br>

Feature/76 scheulde 조회

---

CollaTime/src/main/java/com/ohgiraffers/collatime/project/controller/ProjectController.java
CollaTime/src/main/java/com/ohgiraffers/collatime/project/model/dao/ProjectMapper.java
CollaTime/src/main/java/com/ohgiraffers/collatime/project/model/dto/InviteMemberDTO.java
CollaTime/src/main/java/com/ohgiraffers/collatime/project/model/service/ProjectService.java
CollaTime/src/main/resources/mappers/project/ProjectMapper.xml
CollaTime/src/main/resources/static/css/project/modalWrongJoinCode.css
CollaTime/src/main/resources/templates/project/modalInputAlert.html
CollaTime/src/main/resources/templates/project/modalWrongJoinCode.html
CollaTime/src/main/resources/templates/project/projectmain.html
CollaTime_DB_Script.sql

#86 
<br>
이메일로 전달 받은 참가 코드로 프로젝트 참가하기 기능 구현했습니다.
이메일로 전달 받은 코드랑 DB에 있는 코드가 같으면 프로젝트 불러오기 구현했고
코드가 일치하지 않으면 다시 입력하라는 모달 띄우도록 구현했습니다.
<br>
<성공 시>
<실패 시>
<br>

[feature][project]/#86 Join_Project

---

CollaTime/src/main/java/com/ohgiraffers/collatime/schedule/model/dto/joinScheduleDTO.java
CollaTime/src/main/resources/static/css/schedule/createsuccess.css
CollaTime/src/main/resources/static/css/schedule/empty.css
CollaTime/src/main/resources/static/css/schedule/list.css
CollaTime/src/main/resources/templates/schedule/calendar.html
CollaTime/src/main/resources/templates/schedule/createsuccess.html
CollaTime/src/main/resources/templates/schedule/empty.html
CollaTime/src/main/resources/templates/schedule/list.html
CollaTime/src/main/resources/templates/schedule/makeschedule.html

#76 
<br>
1. 스케줄 생성 완료 시 모달창으로 알림 나오게하기
2. 스케줄 있을 때 달력 누르면 스케줄 모달창 나오기(아직 각 스케줄 클릭 불가, 정리 안됨) 
<br>
<br>

[Feature][schedule]/#76 scheulde 조회

---

CollaTime/src/main/resources/static/css/common/leftBar.css
CollaTime/src/main/resources/static/css/common/profile.css
CollaTime/src/main/resources/static/css/mypage/mypagemain.css
CollaTime/src/main/resources/templates/common/leftBar.html
CollaTime/src/main/resources/templates/common/programHeader.html
CollaTime/src/main/resources/templates/mypage/mypagemain.html
CollaTime/src/main/resources/templates/user/signup.html

#84 
<br>
프로필 적용 완료했고 회원가입 유효성 체크를 새로 좀 손봤는데 내일 더 다듬어야할 것 같습니다.
마이페이지 이동은 닉네임 누르면 갈 수 있도록 만들었고
메인 로고 누르면 프로젝트 메인으로 갈 수 있도록 만들었습니다.
<br>
<br>

[Feature][common]#84 LeftBar 및 회원가입 유효성

---

CollaTime/src/main/resources/static/css/project/modalManageMember.css
CollaTime/src/main/resources/templates/project/modalManageMember.html
CollaTime/src/main/resources/templates/project/projectmain.html

#91 
<br>
팀원 관리 모달 만들고 있습니다.
<br>
<br>

[feature][project]/#91 Modal_Manage_Member

---

CollaTime/src/main/resources/static/css/schedule/empty.css
CollaTime/src/main/resources/static/css/schedule/makeschedule.css
CollaTime/src/main/resources/templates/schedule/ca.html
CollaTime/src/main/resources/templates/schedule/calendar.html
CollaTime/src/main/resources/templates/schedule/empty.html
CollaTime/src/main/resources/templates/schedule/makeschedule.html

#76  
<br>
스케줄 조회 진행중입니다. 
<br>
<br>

[feature][schedule]/#76 스케줄 조회 

---

CollaTime/src/main/java/com/ohgiraffers/collatime/common/MainController.java
CollaTime/src/main/java/com/ohgiraffers/collatime/configuration/SecurityConfig.java
CollaTime/src/main/java/com/ohgiraffers/collatime/inquiry/controller/InquiryController.java
CollaTime/src/main/resources/static/css/common/passauthority.css
CollaTime/src/main/resources/templates/common/leftBar.html
CollaTime/src/main/resources/templates/common/passauthority.html

#94 
<br>
권한 넘기기 화면구현 완료
이제 DB에 넘기면 되긴하는데
미리 만들어져있는 매핑들로 진행했는데 내일 의견을 나눠봐야할 것 같습니다.
<br>
<br>

[Feature][inquiry]/#94 Inquiry

---

CollaTime/src/main/java/com/ohgiraffers/collatime/schedule/controller/ScheduleController.java
CollaTime/src/main/resources/templates/schedule/calendar.html
CollaTime/src/main/resources/templates/schedule/details.html

#76 
<br>
스케줄 선택 시 상세 조회 창 설정 중입니다
<br>
지금 오류가 살짝 생겨서 화면이 아예 안나오고 있습니다..
<br>

[feature][schedule] /#76 스케줄 상세 조회 창 구현

---

CollaTime/src/main/java/com/ohgiraffers/collatime/inquiry/controller/InquiryController.java
CollaTime/src/main/java/com/ohgiraffers/collatime/inquiry/model/dao/InquiryMapper.java
CollaTime/src/main/java/com/ohgiraffers/collatime/inquiry/model/service/InquiryService.java
CollaTime/src/main/resources/mappers/inquiry/InquiryMapper.xml
CollaTime/src/main/resources/static/css/common/passauthority.css
CollaTime/src/main/resources/templates/common/passauthority.html

#107 
<br>
권한 위임 요청 기능 완료
<br>
<br>

[feature][inquiry]#107 PassAuth

---

CollaTime/src/main/resources/static/css/project/modalComplete.css
CollaTime/src/main/resources/static/css/project/modalDateWarning.css
CollaTime/src/main/resources/templates/project/modalComplete.html
CollaTime/src/main/resources/templates/project/modaldatewarning.html
CollaTime/src/main/resources/templates/project/projectmain.html

#110 
<br>
작업 완료 시 모달 연결까지 마무리 했습니다.
<br>
<br>

[feature][project]/#110 Update_Layout

---

CollaTime/src/main/java/com/ohgiraffers/collatime/admin/controller/AdminController.java
CollaTime/src/main/java/com/ohgiraffers/collatime/admin/model/dao/AdminVisitMapper.java
CollaTime/src/main/java/com/ohgiraffers/collatime/admin/model/dto/AdminDTO.java
CollaTime/src/main/java/com/ohgiraffers/collatime/admin/model/dto/AdminVisitDTO.java
CollaTime/src/main/java/com/ohgiraffers/collatime/admin/model/service/AdminService.java
CollaTime/src/main/resources/mappers/admin/AdminVisitMapper.xml
CollaTime/src/main/resources/static/css/admin/adminleftbar.css
CollaTime/src/main/resources/static/css/admin/dashboard.css
CollaTime/src/main/resources/templates/admin/adminleftbar.html
CollaTime/src/main/resources/templates/admin/dashboard.html

#111 
<br>
관리자페이지 현재 주별 사용자 그래프 완료했고 월별 하는중
<br>
<br>

[feature][admin]#111 AdminDashboard

---

CollaTime/src/main/resources/static/css/admin/dashboard.css
CollaTime/src/main/resources/templates/admin/dashboard.html

#118 
<br>
월별, 주별 사용자 그래프 완료
<br>
<br>

[feature][admin]#118 UsingGraph

---

CollaTime/src/main/java/com/ohgiraffers/collatime/admin/controller/AdminController.java
CollaTime/src/main/java/com/ohgiraffers/collatime/inquiry/controller/InquiryController.java
CollaTime/src/main/java/com/ohgiraffers/collatime/inquiry/model/dto/InquiryDTO.java
CollaTime/src/main/resources/static/css/admin/dashboard.css
CollaTime/src/main/resources/static/css/admin/user.css
CollaTime/src/main/resources/templates/admin/dashboard.html
CollaTime/src/main/resources/templates/admin/user.html

#120 
<br>
관리자 회원 조회 페이지 만드는중
<br>
<br>

[Feature][admin]#120 admin user controller

---

CollaTime/src/main/java/com/ohgiraffers/collatime/exception/controller/ExceptionHandlingController.java
CollaTime/src/main/resources/static/css/exception/error400page.css
CollaTime/src/main/resources/static/css/exception/error403page.css
CollaTime/src/main/resources/static/css/exception/error500page.css
CollaTime/src/main/resources/static/css/exception/erroretcpage.css
CollaTime/src/main/resources/templates/exception/error400page.html
CollaTime/src/main/resources/templates/exception/error403page.html
CollaTime/src/main/resources/templates/exception/error404page.html
CollaTime/src/main/resources/templates/exception/error500page.html
CollaTime/src/main/resources/templates/exception/errorectpage.html
CollaTime/src/main/resources/templates/project/projectmain.html

#115 
<br>
400에러, 403에러, 404에러, 500에러, 그 외 에러 화면 구현했습니다.
<br>
<400에러>
<403에러>
<404에러>
<500에러>
<그 외 에러>
<br>

[feature][exception]/#115 Error_Page

---

CollaTime/src/main/java/com/ohgiraffers/collatime/schedule/controller/ScheduleController.java
CollaTime/src/main/java/com/ohgiraffers/collatime/schedule/model/service/ScheduleService.java
CollaTime/src/main/resources/static/css/schedule/delete.css
CollaTime/src/main/resources/static/css/schedule/deletecheck.css
CollaTime/src/main/resources/static/css/schedule/details.css
CollaTime/src/main/resources/templates/schedule/calendar.html
CollaTime/src/main/resources/templates/schedule/createsuccess.html
CollaTime/src/main/resources/templates/schedule/delete.html
CollaTime/src/main/resources/templates/schedule/deletecheck.html
CollaTime/src/main/resources/templates/schedule/details.html
CollaTime/src/main/resources/templates/schedule/empty.html
CollaTime/src/main/resources/templates/schedule/list.html

[feature][schedule]/#121 Schedule_CRUD

---

CollaTime/src/main/resources/static/css/schedule/calendar.css
CollaTime/src/main/resources/templates/project/projectmain.html
CollaTime/src/main/resources/templates/schedule/calendar.html

#127 
<br>
프로젝트에서 스케줄로 연동하기
<br>
프로젝트에서 폴더 누르면 스케줄로 넘어가는부분 코드 작성 진행중입니다.
<br>

[feature][schedule] #127 프로젝트,스케줄 연동

---

CollaTime/src/main/java/com/ohgiraffers/collatime/admin/controller/AdminController.java
CollaTime/src/main/java/com/ohgiraffers/collatime/admin/model/dao/AdminUserMapper.java
CollaTime/src/main/java/com/ohgiraffers/collatime/admin/model/service/AdminService.java
CollaTime/src/main/resources/mappers/admin/AdminUserMapper.xml
CollaTime/src/main/resources/static/css/admin/deleteuser.css
CollaTime/src/main/resources/templates/admin/deleteresult.html
CollaTime/src/main/resources/templates/admin/deleteuser.html
CollaTime/src/main/resources/templates/admin/user.html
CollaTime/src/main/resources/templates/user/signup.html

#120 
<br>
삭제까지 기능 다 만들었습니다. 집에서 하는데 오류가 너무 많이 나서 오래 걸렸네요...
<br>
<br>

[feature][admin]#120 AdminUserController

---

CollaTime/src/main/java/com/ohgiraffers/collatime/admin/controller/AdminController.java
CollaTime/src/main/java/com/ohgiraffers/collatime/admin/model/dao/AdminProjectMapper.java
CollaTime/src/main/java/com/ohgiraffers/collatime/admin/model/dao/AdminUserMapper.java
CollaTime/src/main/java/com/ohgiraffers/collatime/admin/model/dto/AdminProjectDTO.java
CollaTime/src/main/java/com/ohgiraffers/collatime/admin/model/service/AdminService.java
CollaTime/src/main/resources/mappers/admin/AdminProjectMapper.xml
CollaTime/src/main/resources/mappers/admin/AdminUserMapper.xml
CollaTime/src/main/resources/static/css/admin/deleteuser.css
CollaTime/src/main/resources/static/css/admin/project.css
CollaTime/src/main/resources/static/css/admin/user.css
CollaTime/src/main/resources/templates/admin/dashboard.html
CollaTime/src/main/resources/templates/admin/deleteproject.html
CollaTime/src/main/resources/templates/admin/deleteresult.html
CollaTime/src/main/resources/templates/admin/deleteuser.html
CollaTime/src/main/resources/templates/admin/project.html
CollaTime/src/main/resources/templates/admin/user.html
CollaTime/src/main/resources/templates/user/signup.html

#131 
<br>
프로젝트 전체 조회, 보관기간에 따른 분류, 보관기간 지난 프로젝트 일괄 삭제
아직 검색은 안했습니다.
<br>
<br>

[Feature][admin]#131 admin project delete

---

CollaTime/src/main/java/com/ohgiraffers/collatime/admin/controller/AdminController.java
CollaTime/src/main/java/com/ohgiraffers/collatime/admin/model/dao/AdminProjectMapper.java
CollaTime/src/main/java/com/ohgiraffers/collatime/admin/model/service/AdminService.java
CollaTime/src/main/resources/mappers/admin/AdminProjectMapper.xml
CollaTime/src/main/resources/templates/admin/project.html

#131
<br>
관리자 페이지 프로젝트 상세조회 완료했습니다.
<br>
<br>

[feature][admin]/#131 Admin_Project_Control

---

CollaTime/src/main/java/com/ohgiraffers/collatime/admin/controller/AdminController.java
CollaTime/src/main/java/com/ohgiraffers/collatime/admin/model/dao/AdminInquiryMapper.java
CollaTime/src/main/java/com/ohgiraffers/collatime/admin/model/dao/AdminProjectMapper.java
CollaTime/src/main/java/com/ohgiraffers/collatime/admin/model/service/AdminService.java
CollaTime/src/main/java/com/ohgiraffers/collatime/inquiry/controller/InquiryController.java
CollaTime/src/main/java/com/ohgiraffers/collatime/inquiry/model/dto/InquiryDTO.java
CollaTime/src/main/java/com/ohgiraffers/collatime/inquiry/model/service/InquiryService.java
CollaTime/src/main/resources/mappers/admin/AdminInquiryMapper.xml
CollaTime/src/main/resources/mappers/admin/AdminProjectMapper.xml
CollaTime/src/main/resources/mappers/inquiry/InquiryMapper.xml
CollaTime/src/main/resources/static/css/admin/inquiry.css
CollaTime/src/main/resources/templates/admin/inquiry.html
CollaTime/src/main/resources/templates/admin/project.html
CollaTime/src/main/resources/templates/common/passauthority.html
CollaTime_DB_Script.sql

#136 
<br>
포트에러 때문에 끄기 전에 머지
<br>
<br>

[feature][admin]136 admin inquiry control

---

CollaTime/src/main/java/com/ohgiraffers/collatime/admin/controller/AdminController.java
CollaTime/src/main/java/com/ohgiraffers/collatime/admin/model/dao/AdminInquiryMapper.java
CollaTime/src/main/java/com/ohgiraffers/collatime/admin/model/service/AdminService.java
CollaTime/src/main/java/com/ohgiraffers/collatime/configuration/SecurityConfig.java
CollaTime/src/main/java/com/ohgiraffers/collatime/inquiry/controller/InquiryController.java
CollaTime/src/main/java/com/ohgiraffers/collatime/inquiry/model/dao/InquiryMapper.java
CollaTime/src/main/java/com/ohgiraffers/collatime/inquiry/model/service/InquiryService.java
CollaTime/src/main/java/com/ohgiraffers/collatime/project/model/dao/ProjectMapper.java
CollaTime/src/main/java/com/ohgiraffers/collatime/project/model/service/ProjectService.java
CollaTime/src/main/resources/mappers/admin/AdminInquiryMapper.xml
CollaTime/src/main/resources/mappers/inquiry/InquiryMapper.xml
CollaTime/src/main/resources/mappers/project/ProjectMapper.xml
CollaTime/src/main/resources/static/css/admin/adminleftbar.css
CollaTime/src/main/resources/static/css/admin/inquiryanswer.css
CollaTime/src/main/resources/templates/admin/adminleftbar.html
CollaTime/src/main/resources/templates/admin/dashboard.html
CollaTime/src/main/resources/templates/admin/deleteinquiry.html
CollaTime/src/main/resources/templates/admin/inquiry.html
CollaTime/src/main/resources/templates/admin/inquiryanswer.html
CollaTime/src/main/resources/templates/admin/inquiryinfo.html
CollaTime/src/main/resources/templates/admin/inquiryresult.html
CollaTime/src/main/resources/templates/admin/project.html
CollaTime/src/main/resources/templates/admin/user.html
CollaTime/src/main/resources/templates/common/passauthority.html
CollaTime/src/main/resources/templates/mypage/myinquiryinfo.html

#136 
<br>
문의기능 일괄 삭제빼고 완료.
<br>
사진 못 찍었습니다.
<br>

[feature][admin] 136-AdminInquiry

---

CollaTime/src/main/java/com/ohgiraffers/collatime/project/model/dto/InviteMemberDTO.java
CollaTime/src/main/java/com/ohgiraffers/collatime/project/model/dto/MemberListDTO.java
CollaTime/src/main/resources/mappers/project/ProjectMapper.xml
CollaTime/src/main/resources/static/css/project/modalSelectProjectData.css
CollaTime/src/main/resources/templates/exception/error400page.html
CollaTime/src/main/resources/templates/exception/error403page.html
CollaTime/src/main/resources/templates/exception/error404page.html
CollaTime/src/main/resources/templates/exception/error500page.html
CollaTime/src/main/resources/templates/exception/errorectpage.html
CollaTime/src/main/resources/templates/project/projectmain.html
CollaTime_DB_Script.sql

#110 
<br>
어제 시현할 때 프로젝트에서 오류났던 부분 다 고쳤습니다.
<br>
<br>

[feature][project]/#110 Update_Project

---

CollaTime/src/main/resources/static/css/schedule/alertModalConfirm.css
CollaTime/src/main/resources/static/css/schedule/calendar.css
CollaTime/src/main/resources/static/css/schedule/createsuccess.css
CollaTime/src/main/resources/static/css/schedule/delete.css
CollaTime/src/main/resources/static/css/schedule/deletecheck.css
CollaTime/src/main/resources/static/css/schedule/details.css
CollaTime/src/main/resources/static/css/schedule/empty.css
CollaTime/src/main/resources/static/css/schedule/list.css
CollaTime/src/main/resources/static/css/schedule/makeschedule.css
CollaTime/src/main/resources/static/css/schedule/modify.css
CollaTime/src/main/resources/static/css/schedule/modifycheck.css
CollaTime/src/main/resources/static/js/schedule/details.js
CollaTime/src/main/resources/static/js/schedule/makeschedule.js
CollaTime/src/main/resources/templates/schedule/alertModal.html
CollaTime/src/main/resources/templates/schedule/calendar.html
CollaTime/src/main/resources/templates/schedule/createsuccess.html
CollaTime/src/main/resources/templates/schedule/delete.html
CollaTime/src/main/resources/templates/schedule/deletecheck.html
CollaTime/src/main/resources/templates/schedule/details.html
CollaTime/src/main/resources/templates/schedule/empty.html
CollaTime/src/main/resources/templates/schedule/list.html
CollaTime/src/main/resources/templates/schedule/makeschedule.html
CollaTime/src/main/resources/templates/schedule/modify.html
CollaTime/src/main/resources/templates/schedule/modifycheck.html

#157 
<br>
커서 포인터 안 된 부분 수정, 폰트 적용, 셀렉트 박스 토글로 변경
<br>
<br>

[feature][schedule]/#157 Schedule_Final

---

CollaTime/src/main/java/com/ohgiraffers/collatime/mail/model/service/MailService.java

#156 
<br>
프로젝트 참가 코드 이메일 수정
<br>
사진 없습니다...
<br>

[feature][mail]#156-메일수정

---

CollaTime/src/main/java/com/ohgiraffers/collatime/inquiry/controller/InquiryController.java
CollaTime/src/main/resources/static/css/common/doinquiry.css
CollaTime/src/main/resources/static/css/common/passauthority.css
CollaTime/src/main/resources/static/css/common/programHeader.css
CollaTime/src/main/resources/static/css/mypage/modifyuser.css
CollaTime/src/main/resources/static/css/mypage/myinqiury.css
CollaTime/src/main/resources/templates/common/leftBar.html
CollaTime/src/main/resources/templates/user/signup.html
CollaTime_DB_Script.sql

#163 
<br>
발표 시 사용할 DB정리 및 CSS개선 완료했습니다.
<br>
<br>

[feature][DB]#163 FinalDB

---

CollaTime/src/main/resources/static/css/schedule/details.css
CollaTime/src/main/resources/static/css/schedule/makeschedule.css

[feature][schedule]/#165 Schedule_Css_Update
